apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: questify-minio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: questify

  source:
    repoURL: https://github.com/axelfrache/questify.git
    targetRevision: HEAD
    path: charts/minio
    helm:
      releaseName: questify-minio
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: questify

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m

  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        - .spec.volumeClaimTemplates[]?.apiVersion
        - .spec.volumeClaimTemplates[]?.kind
        - .spec.volumeClaimTemplates[]?.status
    - group: ""
      kind: PersistentVolumeClaim
      jsonPointers:
        - /spec/resources/requests/storage
        - /spec/volumeName
        - /spec/volumeMode
