---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: questify-auth-jwt
  namespace: questify
spec:
  encryptedData:
    jwt-secret: AgB76N9PVSG4Hy3NES4+oIIqhHHPYrpRxDCFWewXdwDKr6rxrrNRJD348d6bUIGs/YbzyvXjCOg7hNZ7e3SF4sPUkiKUmYNwRy13qP5N2PNSxbM8fXAjKWPEZkDyUUEqwG3RjHdh4vOmygoPqUpVZzs+ZFIF75+uyNf7Q4GZhfX5dgmH2yS9yD88piGF5LAY4eqv7UaLXAGsdRlfIkYO2/J6Cbq65lSKg50fun5PNNCGsCfsln0QNV0pprnKjgqVRy4pCn8QHILDmESsLYeza/ZQz6wdkS4vpgft8UjvGNlLoNOXK5sFDnvHYmn86vWjXVesSXOemXkW8t+z4HPXGLPUEOqDU+ZKFGqimlyzKJzYi8e8UMCLEWK3Q9TZeTRcxw3uIYGY2OmbHvtJSXq40BKmb4aK5vMA8kTIoKam3tB1NIUxjtiMSXjnXtSKarZrCJkqrrgg2LlrS1VGlLzc8HLhr5PdjDjT4ZfPUn5xHFOhAMmHy2WkD0Vx5zBsu/+/KWnpnzsocG0UyPZspFLFX81QRwiuk2BmD8Gxz0tiuQvLsfQj6I+Bctv4ivC8hoV2D1vcyR4DmCBObERY+NvkiSJsu9YA6LESFxvDGTpF/emBhxg7de+1JHJvei4Ccv8yaq/2MltZ2roK9r+tyn4notqwgXuwcu4BZ67nVwkauJN3e1FLHzzqzmsPgV3P1hlAWqG8PbtViecOHlGhMEDQwl5mn9hzUOvnRXKX/uBE6hBski2yt7kqTyyIFf36szGJCMybOuZMw8w2XhghJ/bT6tmg
  template:
    metadata:
      name: questify-auth-jwt
      namespace: questify
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: questify-admin-jwt
  namespace: questify
spec:
  encryptedData:
    jwt-secret: AgAO9+S7M12gfF3ptgZ33kvcto2fMp/J61kJ9fiTmYWVNkNKN2D7Z/cPYGlL29lXc1ACW2a7X6zZhQZjTaqSjhX69G+27w+pAChxEuD1Jp8F/HiaKqb8hW4l+opduJomtZm1/6nTIspFD0qkP+jaL+7FOT+URTkbFvpq40qBsjuoItSvUNwImMOu6j1TMgP7TTJoOcFjqPwt28xCy/lXYGuk4r89LpG9FhDKN7FUuQr43dsBkuFZj1GQjB+qOgoByUtvs4a+BUg7qG9OsjLKLYrpwNd/g3s0b6ZN9w9gz3uZppKyWdyPgkurXBKK/MeGLGjF44LX7h4VsEgX3+qisqtPBrB5w99jD+5IrSPSv51qrmEtuWODGJiZeViPDDTVrdPWBs1TZn2EgNQ7aQ+79nanmSnGckaQO1zLf8apSpwqNiGwrPAkoUE/rvgWH5zoiDy2oqCwQtT4hrEbf+p41WfcgTUNLS6/1IboDKsVpA8RadXvAKPIJSBjum1As8Pe2ka19ZyjK1ynhXtUgyD3AcIw4kOd8oTgqOyqWP6oKamn+i7PGEIY9OlS3s1dFWxrzZsgx5Rp8bE8Gt+cOSqqP0KICGhfPjIEsKuO+nCOWuYL94ziBkCR72CpOoYaiattDALeQrV6FoYXaKGSNUlpYV/2rKfVNVZXQyXwifb5+E8U6/JFItbgYDfwmKTCPKXq0fMMmYJSubgmo+DiJR0GdrQq3BaKx866Stbj2gYmKlZaqFFbYcvQklNpWaTxncfqs9fL49OTMqg91GilifVDZOoz
  template:
    metadata:
      name: questify-admin-jwt
      namespace: questify
