---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: questify-auth-admin
  namespace: questify
spec:
  encryptedData:
    admin-email: AgBcO2h+nbheGVULSynniaCzmSOMZLX6CTrISNR0gteA5ilp4ILZqRq8TZj3v/F0Bc60gYdtF5GZBv3fk+qT4U2LooNVe/pyQ/LzBF+ka8bBJe6QRCRojDVJiVahcdCLsDH+v1/WOrvuICmjnR3tz1k97n7/OYPTlXsR5WbH0f4wRzlbQMOwZuoVly3y2Nxu2dx1c7FF9dIXXeCPl1zoJzLZ+PDdoATvz65AcnsXaa8ste2JG4rU07x5Fi2wIpPl50qdvh+qQuXvU79R0Zzd96wxmeuUXYxoWDxLdtlmxrHAd1VTwznCSEUKkjOWZMuYxeM1IpprC4842VeQY3L8Kf8Bj28v3iByteUbr3cn36zTDWyVm1SMNNBjSdxwfovLM7cQ6RlzcZchwv5KWGK1fqSnt+3UJquufVTkv7r1x4uOKYhk2BfODI6lspefaAOI1qVHAZyZJc21xSTq709ItzgF1GJ8jh+q72DPCkMuxE1z0+btTPeNRQehqr7BmB5ExeHKZiXeF34G/9dTf5hNAgQtIPbns43+vDqqh9y9QYr/4+eOxbChp+xq8uof/TPOrbr3DQhnkMTfqrrf+56BsWfNsviz5q9rLnSDGQD470O/9UdbQ8PVui6qVuGmfHPd/v4NtdBh4KnVVoKCaZVc0VMkhfeapYrNqJKOP5LTUNsqadk1VxpWEVatBpYYO7W78QWKlvRYdAx6Fmt1ha4wkboiQ0UmAg==
    admin-password: AgB2uFzu14TZDDjwkZUlQPdmS86XHcJR4bGB85OIF3lXUVXRXipiWg4ZCKPPGxZ2O/KznDve+w0wuajL9XrWHrk9oThtUVB/qGw+vyj3CJp+tHzrlRiAulvDglc26sk0ut0gnnMbpOyopNfn1tKovuRuYaK3+0/lNq6AqCBXhGAhNNcszvMSEu7V1JXSvNo465bTMdNXgDlrgF7dUj6z/56B/Xj6pHPCUPQq6nSMlGs1fOoRVE8O9AkSeUI0Zzhm4JX5jZeqjqZCuvQm/OHw64S0KKfCGMqhcSnYS6XeT6QaF2/0SLdce19RNhut16tl5Bd6DfyUnB+HrGM9D6l+IYSoiiOSKLGz2KiZ9TTobUIChxTmP9mnhyqgoLSxI9OZAo7CmU2vHK2+uD7gLAJIrxhHu7ZFg/lsmQ3VXL6QmLRGhdKoltFKk379H3JmlD9/InlAxIYt6YBin7V1/6ZEiDboNhW6b+/epPHsL5vGID92VHO1vYkeEfNH+EP1EH+cv42Ar3SVMGGsCxQwlPPuhpAapmkHVAPpk3OQw5cYPcLWQ/J7LcXkCWIfmxulD/hlSpNgNgmrkXC3qRdrjPTi+kmcX3ZLoRXfU82nfX/bp2fr4144Chf1Q4nAHGOXlWIRzb8Zgv1JvRJZLEFSP8fFWCi0W0EA35ShqDdvkSIWkswbgdNYjv+6J4e7epu8GDxAQfQEnwtVor14oXvao05HDynK
  template:
    metadata:
      name: questify-auth-admin
      namespace: questify
