---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: questify-rabbitmq
  namespace: questify
spec:
  encryptedData:
    password: AgA4TuCMDl5fv+Escy8cGhjg+nT/DKUdOPYvocWXdGYkQl0vuUk7bQ1xshK7m4fqdmuPTBFRMgmJMbPdoh+wNKZ6OBDBdxoU1jKb3z8dYn0LHltmytZIibNujbjUiPiRw7kBgXZ7QV1X/3rG1jgDZfRYmYUvxWlGNrgP2cvRoTBMO0Ud5E09lNIPlPd9vEpUKH465MqwK66vVZPiDRk6RiJKEpsHHwrhnlJaSWfNglAS3jOTqb37tDIs/1lAifaEr+npLtkmvunHY7ofYYW5pk5Ow+1LKS6wRG/XQx/d2nfMKsBqaEcnkrDL2H0Y9uZfZ3GE5Lxa6BhRVw4aB01w2hg882DkzY0hmfVX+zR8uJaYrBFoiUBbr9ThyLV/qyZeOuCDB8ytQi+iD6cLTX8e+7X1Yx+50Orwglt5zT/7Og8ExDw604I3HBOBVSTG8TFERRc5p3yPeeeRySLgjDa+nAiqTtlMhHsYRAzQoAbEgFgDoqbHoFSMXJ9R/CRSB86WWSTdJ3vmovk6nM2HzZ6Y802FgNbXyVhKBOonnapiI3yWlh0kcwAZicMwSDQN1jqYKepN6fPGU4X5jnaUrKHh7CaTE5Yy6zpOktoJNdwteSgiavG4+rUg0BQ7Zgf5c0XblBd7qDUeZGX2VcnvEgyVjpq637tvceUSClo14l2C0XWPMSW13tZHdyEQYu+jg2xIxdb2VpYU55oElv2Stc/SU8rNqGnnnkYYxAMFQhSm+FJmtU97X9hAEKKe+Eeh7wdj7Iw=
    username: AgCrbxygMhFlg38jitei3vhrqErhyyQhy4hkkXZRWwQRHaBhl8DM4i++YEUxKjOQRrOw0BWMUNSaGhl4VehcGT2k8yt2li+CnhRIURohkzU3MJI7yZjW8aNlCRqOjs+emnZOt/jI5/KtoYmpliIDdqwgfGNCVAVPVNl3IoXgh+m/HCOlSYq/RAY32V+pvciM97A1G9mDh2MhlsdWDpgJdPA7qg1gFrVi5gCEBzs2p9nfDPJ6BtYIRE6KcRr4n5+tbW7a3xycpzXfQDoYuAIJzDD1NK5paGxybr7+Qbv+TNR0f7sSdIM7kiDOsWRAqeFnMJO1t8DZLY/m+2SFc+QbhWb/RZgGU4t0EB7WfVLhJjvy6DyPArAjTP2/jH/pRltwPFPCO+R0tlJHpXG5DEe36rh09J2R+G8SXk72GAgJiAH1/EqJY5TTzPXpx0Tzom5mFOyCL1Pp7NdB2ImzFz3R2CZFc+8bhbyYDv4R4sd/SbrQYiBmF5Pk39dGm+JQYnbJfcEG6c7xfdjreSLN1egfF/Zf7ypG96ACFMcrVrdr8ZSiLrwliYHatYltgjPcBgDcZvfeBKIjoja9SzzC0vJsaqbDr9lyaQ2XmhBxm5UeJvC9WKFSkFWe8a0wy0pwPykoT2n6pPKANxqAvejM8aa/V+lABYLHrA4z/x85PhnzHfaWSS6S3F9IpFfuu1c+QTIdSKOLkEWpr1cDLg==
  template:
    metadata:
      name: questify-rabbitmq
      namespace: questify
