---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: questify-garage
  namespace: questify
spec:
  encryptedData:
    access-key: AgAuL9iniQ7s2ej4F91onI3XqZo2sT8sSyQ+0TzCCFN+TZZK05giF4Ha0wJeQwCHuS2kehn5Oq0fy9xu0kksElXjrszOcXSjDe2ecs8KK28Xb+H4iAwqUXizapeqe415sK4Z7F4FQrgRi+O5+/xS4C+d/2g0PHGTnLUUcB8wkBg21qgH8MRNrMM5aDkIF25CtvyLi6ldVX8N6gUkeyyGPsDWGNwFAymK8p4sBfqZvCZI1jRn3zOo8rsfVldJkuD800erWwbUYfTy2GVcFYdPO+IttDtidMU2kpMK7TehGG7mQ+Kuj4s+NPv+Mnmz9y+ok7fRZKwo7uCH6b0VI+wnptA9rnVjL+olarK38hoAUq05gav7HUoe3Cy1WkBKq6j81JMjFJn7+PTsEhYRSyfFdNbIl0REXltw+10OHrPI918ltIXusRjL3VvMgpD2LM5aKgZ1zwjPMkYmz4LB2SN78/0VFq7EwMAKoIgIyPBtjYZCwWEF4gEldpGXMyY/vDPJw/qTjVfJc0CQ590/AiYmgHu5hdAr80H2WRFEK3pTdI0ISpD2rVS7dVjW8EveLtK/Q1vELuo1BCuGK5q5bp+6RyoI37FntDE11XlB/Hc2uteSf8UBOYFdDZpSYx0RyAfrfx3l8fqqiZGUafTN4HfsNSNucieRcLNFAeS05Clrj/hR/b7h0xxb6GZyY7pcW0knyiXiKa/dxKMBdp/Ep5YBSrSDvANenGxoxvWsUA==
    secret-key: AgB0e+Scg5cH/a7PWJVPA+d342f7v6cEDbbsd97ai+L3BqRiFUw+WZaNhnIvCYM6EnOMpwEcvh01uXabhGd2ePcUPnBxhmL7UUWzVHYnFVOX1gaVEzGWDut4lli2BpKonvgzmPjagtnB5djEfQF0wBClMXe0xKHbWBGBqy5CjAT6rx9uiLEQ5ctL8mYiHefsSlXB14d0q67l1gWVqdV/y5n4nr+qoaJJS+h0Q8ql9RksJMDvyXND6KOj5EiPwySmOtH9wcF9cYtjhrtPD+3HYrYsCcLhDdynz71YBhsxpc/QCwN+9KB+N9nZ/qMpbikgw+eJIgV9gTRdkNkjeGG2M3tE09fIRf7H3u/XqeynwcJdvupBhBjzYMROVRxrvTenMngF+xM4NxmjGPqiuXboYUjL1Y/SshOMomo7hvEX0e3FRQxlE5X4szxVA/yk/6moVw2TNa/YbkK5AenS+8DybK3AQeCeTS9FC2wGk/MMfCiJbSeF+l5+aUnkXS10MFRd+/ikW3wupnmi7bbXdPWxXdPe47Z8JDBXsDQzNaz7WWELGJGge/HYX/H4kL9D5kFfRB63CVx02x1/5K1t7qUvVYAxostIAWmCpW8ZMw/1eF4GFuUzxRYbZ6cLjOXA/9ZORHeM9JHHA5JfzIGeTz1XBko74+9QsBdImirzF4NUbqaARYeHjyjLrN+dyGiQ94e5vkXNDP3g9B5p+WEp6DpsY6ZuoHIrVpoR8u7V8qzKk5JlyCuDkxTEkGeRbNtWLDcZ2FwyQ25TeTxty2EudLUYszAX
  template:
    metadata:
      name: questify-garage
      namespace: questify
