---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: questify-auth-db
  namespace: questify
spec:
  encryptedData:
    password: AgB8MjCKTOV8y57H3K1d/vk3lz2lWca/GR+umDigLp2xldSfdkIzqPIsFMxtdXNL2zU2GNEBw+M99C2bXpIWrfvWnxEzSG0klsLqXPqfM66YOgdnd1FI55EAnKwkANeYUj37+QKItvffoBoEQuMXIXKVtRb/zg2e0AUg60b1wc+kBNvPTlCUIKjWu5FHp8jp+bVXfUWEJN57hb6j5+fWSK+OYtewiRFeNMiSemYuFyFOzbxYRMg2QcoEycu/QMWm7KELv0o31I+frIL1/PEjyFY9SNainozbaBUkxT1i3md9gYkleNGBkq9vWZOEGP6sFkOnvsrKn6M7C8ajnKQWinIg03WTPXtSMCSsr97PQnH1hyN+JEh4UB5IFWMGViSPU4xX62Lvh6RqHRYyHjdIl/GoWvFrT//TDb0gBA+F4dq66DIiTPHqwNvb86KYrDcIj1S/RgpJC4s+kIyS6WgOUeJusOoJbs4DHm+D4id708YULnZzjGGUp7I9FZaCMBkm51aYEJc7AC7mUCOl/NjWAaZ34B+rNqbzwnYXUnwDVKNQCK78zwARUW8j5E5Y7TVol9CCrb/MKrAPPga4gaiwr2RHgqFqQ5V/VG0HQu71rOYYrdcwGlVdO4gyRm5BuNvUMv+ahi3ZJVJnqD77SNyqBJPR2JCUmFzVzBoFMkF320+ZnvTHby1/pO4jM0RE76nAPUxRC36dc9NqSlytgrpB5LUorVVXV1i5YZpCNB/rSVEnlrDW9nTEm+3mYRFs9+NBQT4=
    username: AgAlsdPFUB0nDGU7IgCk6uskuDASRcVr66BWf9/zw5iLfx2lSsy0dAny1Vje6KYe+JVjhAxcdAw0Rn5liX9lU8N506+utif2PgNVO3yjrJAIHcTQV5rGyECumCyIUdDVtcVmXpSnMdSNDh5kSUSTN8WBcru2S3Bv+LE/+UOYfPvI5V2v0FQFycXgXZieeOsUsJumL/tf+GTwUc/e1dVufYq9GyLXW+B4PaZLRKgiwMPMrE7XxV3TsbStlb7/Rl6dy3kpr22VUMXCTuunDhOogWGLZQWozz1lpOcUuA2qmHB6LDtQi0Iz3yy967SaTZoUZB5EeDu6DjqO32S8TNxowCmsUGgAcdxsDzaQUbTIAyS2H9Apo+sokfnOpX+xbP1jMgKja0ajy6fzcZuJJIELrjlUDWuAeajz5IfScP26aWk0Zr2Aia42f7N0bGjF/stRPpttUnd1BZPqfQNcEx1Y4Gff6tF7SxZhKWlO5HmRZV9Cychmr8hYD9u8siO+Of3+2MCcRSYfVC2wos+H6Art6YXJrduFOjW4AnzU7EVanWzEHkPHiFk/VWaqFsWje7W3LKVXEik88CUXJjcN5KNk+J3icT32bcNxoOmU3jC8eXUwqI9g0uA9o5rQXaGTizYCL5SLTRGzHNOH/9Mcd2h+0mgqjzaPce+9nmNltWuoEBwMW1+pOuVApLeK0uYTKrFd73Y5C4/9oW2Fkg==
  template:
    metadata:
      name: questify-auth-db
      namespace: questify
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: questify-quest-db
  namespace: questify
spec:
  encryptedData:
    password: AgDGqM1PXI8uSSU1927Vk8IJ9yazTsY6Y/27MpfcAzfROHuWnWpzhMY+xv3mv5wHex6z3wXq+ELrCdUxFn7DuyyDkJNwCN9kbFy9xWfrjkBrRCaKxwCMuY1ly7V+kIyB4e7b9BVT5ooBxJJIyfWUOin9nbFLTf5AQa3+E7RAvP1NuRiYR+UeJCfHRbgCJoABAOiNNs9qzeCikxvonetAPvixiBkX/tDOdgbONVaykzl8qkbUb3CIxb4HWgD5vyzoOCLLDR+NvSi+puyHNEbUzg49EQwJI6dUyhYWE8omt1EgD/vWq3Q+HWteCtOJ2dxlPjO0TUgGeB9qlW1t7qiKqK1Tp+CcN7BtaxBPUfwRLu7uw/rj7g/t4dKQ0zg0rQBlta+iKVAN5nZswlO4TEde3fGy91eAoXYB+jskkCsCUlgLdoJlwMvOCEm5sQX2LYl10/b7h/xrvdEj35TIv9qC+y7a+wKcKidtqCjFgMyD3lrR1hE0Nve08qXCMF+GiRngPSSupGwp9TVfKgvyhNta98iHEpIGqGQQe1gZlpFSE/IvHSRUc0aCfw8fqFrJUgxkOs5ZaVuaTrHwnEvuxYdxmaxQG2QqIUexm8ovIFqqdW598i6OjjxxaAUtcfYIa7pitLDT1wWvt63Am//FUI9PghDxFs2FDmLl5ERbVbP3hR8r/3WNb/FN+rAmUjdolX7WIEcFiLuNUvpoz0y7oDmn9BsCtXnAGNkmaR0UPTZj14aEfw==
    username: AgBD20+8ddyO5jVdTXagIujk8x0Su62bVbMzbFO/vkYx6ioQc74CbiBoaQ5XHfNOCRn41RSEqETm4T+PY7tQO3/N9U8ZGaJ1Xf8YYYk1i3SzGDPP00skcYEjBDbg9l+8NGN9CQNdsGQLkEVyiZ1Ude8lXpp40E/ohA1GzmtqSJCpwawPU38QMv4vRir16vW1d8q8C0I4OPJlD3sExK1uxFdNZmosI2M93e/IEuDsehcfN1vNrgnKdqqpaNzfUEZDn/wE84BQ9btAEwBBqrTb+AKT0gTeq5a3J1p6RaNc6NkxRQfupsDJtwIkV23E5AtTabIFZ2Vj3WMcEAuyTFHMtP5/T7PN3sy4lnvnYyOepSqZmsbkZJlyb1x7mW4pLEEOu9k7CNk/lgs3VTtBJsjM1tbHN0UBUjRogavsKdX6IAGNdRPponL7FbuioibKwnynKostKGNT4x04DK4W4yerqU0cK0INkGA7/vq6EnRMGpBf9XwhBRSdxihAhfQlhEaeOQcuTA53JGHl4kqVcYrB/r8WYUdSFK7zBFsVUo3VMfn3m4NNe8GkNnnwGo4gi/Zi4C89Lv5oYeSrYwGNrNF5yr9hjPnc3RsLN109f7XAaa2ZuGdL+pPSio/vniBFSeidsyy4+fwLTsmJpHb+uJ09Saab0cB5nmhSpkqKWXChKq0LAUi/erhhTZFR9gqKE99WO2sizzXkJaclKsM=
  template:
    metadata:
      name: questify-quest-db
      namespace: questify
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: questify-project-db
  namespace: questify
spec:
  encryptedData:
    password: AgBiZtjYBQu3u3U/ZAWl4k34QbVhYieKWhv0YEce32dso0dCYse0xa8nWnezn5AxCEo/nu1csokZx88ixMUAJGpImCineUl4oCJClCGOfzbEKeHl/NfQlZsBxE7wxkroXuLstdOAokXhyZd9o0h0DPzhxWMWZigi9IwkPCmh84hYaDjcl5zZtoNr8jupWXIr5GLd8s57neIp0ttganz7b3RC81dEhHSo9acmIPSmGCn0t/C4LyAq3rnAo7JqDPE4977JQ2r4uJlaFQ9BXxe467szc5Z+WPiVB5+vSOYzGw3inYLgc6jTUw92W3BzM67rRyjGX91x18GbGoSYkjrNT2L/MB9uhxfOoX6g1dcPIbqIkXoeMsT9tjd7oEZTjG+nbtCaGQ8sCSsin1pPJE0mbfR11F6cNy9N0UsiZ7G7U7V88XvH2vwGkRx9VWVATdtRx5H8YwT60Sp4sq7pLADtJ++KDxmW0CBdtxiuCrbv97DAvuCYvUag1EPGRhqFHEVYHNLrV0vWiyTrVGA+q2U67e4aWmgXAEjd8hw92LrQ+1cynYHXPL03XZ4lCVLBi3F/+TllTLFweiABEbO32x6RidUteQntmEmJUVwSd8EC5af61uHdIov7/oESQ7PhB2h+ejhBQnnrzdy8x/IiljwgvVo92DK/vUIjqPPj+3G5t6yb4vr7J0OKUyxi9tlDln2R8d4XVAOrUUMdzqt7Ya2LpkZWFfRRCP48XR3L7pCKYjXjDg==
    username: AgCFWOQpLvcBlF5hWfT4cnU/Kw9ZXiAw0UdA1Zw9AZr1ITBIkgqMPHogG3L5Maw1DuJQt4eGXulQIG7vMilsqNPIKX/Yv8MqtVBHYzaJwY5w4aOZF1u88CtJ90lTMpQtKNW8HR/kpvEuL7v9XzFFKCUbVXksMnDR4oLnRPDjVxbqjLW5/rERIJvYsxTFyF8gZGT+u/YQUcsfHTCBZAbaJmSXMjQnfOKTV7a5ULyp3tyvmMrYfh3QgBJNXJr2UiP4ibCbHh/olRb6lcVSv2NVcYLl20LuCAmZDcR4Z007lEwRB4hwaishVS05SOVmbaWJHPaxOunZykqwJBqQub4O61331yKgA0bZompgdKD0mOkrIF8Zjru2/R4OiddZFXoiYJDGo7AQE1Eb6LWzNiKCZNBQ/+cWZ3IMq+CSEAaQ39b5J4e2BvU4LlXIikSqtmVTMYV4RCEjNJ3qapjKV5QHJnuStm1PPmN4aEKoJ/vC30rLQKR3HqJHpwDPWFMC4wWizFziHjyjrnuDim2BC1wloD550/xLw9XB+LfEATtP4LxbGDdEVvuhyfyyuWipFQKSVlszLh1047IiK7Kj8ckso6EAUXMQIl9Uro4es9ZeEGFgGUa0nK3GkQAFAFtgIiAgSs6Z/WQmf75CMd+taYBXjzOiT2+8LuJp64e5IWoXVL7PIm4EkEJMr4J0wxOhyXfqIDxMdcw+L05eBIkSPw==
  template:
    metadata:
      name: questify-project-db
      namespace: questify
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: questify-progression-db
  namespace: questify
spec:
  encryptedData:
    password: AgBAMo8gUgIMm/8DFLHo81T1V/30CZMUK2KPkDTY1E14d4Kb5WcB941kzKXgO10/PGJR/0G6vG5CARFtCgeetvxl0UhdzRu8SQvunm05NWjoFiBPtPGT+1z9nqFBdXV0XsZLmt6INBcxk0WFN35LKUrSnjQwzjlne+K10oGsk6DYukv6zLgc1RZIkBYidYc+JrDs1/fXQiqcThC3YMkDBGGYL5k1P+7+59SYtlS2PKz1ACESFcNlaDPQvRNCuX7I+YCeEq/OtOe2jXFJEowlQsNQ1NouLN2R1rrH66xYbDvEn8A5Dzi1X943/jR95gJDewWCWcYHdnyPdE5wnusAV1O6vGZZonlu/ZpTFGnjDERHBf9UlK9GgwJB2nNfkapkdGYCTjpflhXvnV6pqnZtsGclZkMWLckHLKGwOIjwCCTcIc3HK6KVn5c3MGAdVjojvz427CRDWqA+7nCTbyQAkywvEsVgK83KYj4C5j+LfYbUEWP7CVaS/Y9ZVVMydCEwGCMDVrdudZPaemvHD9cntVkdZ2AWRCdCO5U1f4uEh8tBmXeTDB9F7vDjjs//a6a8hKL8PkY2BuCh6i+PFtcMfHf174x/pv9mKDLiPH7y/wzdg6W27BOXwq2CHmb8pJ9yxfWq0J9BT15nO+5pC6scZfgcgI3qmeD10l+5vA7uyEfRszItktStsXlSuPrO2haXmzEhJFXlS7K2BJnCOP3b3tvvcGGhsa6dyB5TWgi+ttf58w==
    username: AgAHvvZxcEa7iFLcuEgX8v2O3WEnqE6YyDbrR1Y/wKLhnvnJWy81Mc40lyodrX89G/HuejwhFIy+p5HEOIkWCWoAeihhukOOvl0y1XAzqDF9I2qsZU6rStILC4sF2sc1VtMChgtIVHcRb7PYM2hqrH9SB0/0DYbRzWuS2ZXC4NyHfUC+BZy+mJmW73Ux56glt3IkXi719Yah/VQ+cr0VUDLOw8f39MT7OIECY3l359+nfW1ZlaypeCj86NvJkJqnn8esddCaxY4o3uemw0+7/QDfFqUM/vHU9TukvTTJq+ThjMavNVVGwXO5EhVLgnrkqVHj9U1S+G/ccoocZ6Ks7Q3wIVykwonVLzIlOgKBAwJwsFG6M2SNW0YRHyXaauJMo1TNTxdOWIc6fo2tDo6YgfVpU2wZyp3dblJUQ7sJlfc2DX9LPdEn/eMEgOX4/kRmhVMlqr25xIMB4O5yNv49AS1YOLLpqFuTqIW0gmQfRRB/Af1NMv4dB/mr3jx4hv3iQeClFrDMLtR4eSlQDRLTsUEjtSbTE8kfyizbhWQ8HYj7B2SqqJ+tqWXDWBPSufUpjeUq/fCDvgI9rkKliNLTl0JwVrKA9qqlPp3+kHMfWsaevNGaG8GQgt6soec8z7VmVD8Ojfg9GmsdEQRwEd1K/u/v4DYe7yuvOfFt2u7zgqobsxWlJtWHu005VCRuZJRSs6SO9h6OThkhv4TUHZA5Vgw=
  template:
    metadata:
      name: questify-progression-db
      namespace: questify
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: questify-stats-db
  namespace: questify
spec:
  encryptedData:
    password: AgBe1Gxw+c68e2larQQHPl+dopNXzIYuXRB1aOCvF+YyQDu7s0auFp+vpMBsgLOOzkDisz+pjB+P/l53v8iVTv9O8VsY/Z2ibBdpxKpBELJSsiIYdKWI6q5wv3tImI4Wyq6oLSztXMUDopQNH9wEACvFZOxG950B8wIprel2AuVPakpmX9hV9G94EXx6GOIhqaNNGbYpSzCI4RYLP4HJIn9iqi5HagMzWFis/a+Riuih1R7j6rN9i6dGwwVK/7tB0RZYGwBKNxvF8QxTiueLkMH5cJ3Rx88Z0I9MScVAyl7UBGafMTGiIBeYMM6ldZ+XTjj8Rr1f2gcCX6w3xxrsRTM9/YVW/IyVo96k0aEHq5MiKHyRKAeD/0IDFxnoz6Zr74Rw4VNUvH1bUWT3y5ILK9Hcmb5KiA7e0ntSz+61foBFh8thZXtcnmRLS3+yrVVANC/al8chaAEpMt+2kxiDd6oJYgsxyjtNbNMX6jl+A5N8f5WlFfMCHHQnZ4tEc3N+k4s/0dy/uP+1LGBC7G7aa0ADhqxeZlQwKEoQr7QtiwRzMXdmrloMACtM1whI8Iwh36J90XXCn5jy6yip+IK2UdNOmHapwfQkCPjWxxKFVOloKscQ4IDtSuJFx0j50h1CXkMbf+0Kj4oC87gVOajmrP8Qe4ojPn0Gb1FWEpTib25Tkmlm3e4ot9f+j6REVXWo45h9f06VDRPZHzHYm3EdvkX6A8LLDCrKvGnpilhZbfu+Kw==
    username: AgBKVRsMc99DwEn6A4RnIXWF/aZoKVZ8pZW0GMh2P/AZiUgEXCl6bDIm8H63V9fRJm7qc+4GRJtJbO6d9K9zI7aD31hMwr0q1bOf4+WBsXRwb7a9HYfNWuPQ/PmJDhvh3KJKIItnJ64y+mr7glKOtUK25jcW1XhKZ6KgEPOfh5xsK2Ke+xg6AvPHSGCbTUne8XEuUfewW8Nm/EPPMj+XEF5WG46s5BaL96TkcW+IVSZLeJGWcc60Fs2IEwvFCcsyqSM0jEedJZYe2MR922za+jnWRKcT63s87Dc0WeSN4I+PTWYsPbPqEb2+D+t9p5wUlqgRV73EB7xNST3It3ra9TojltF9BrkCAKqMrAWkDfDmyia7LenYSiDt5Lcy54xco70WfF/HWuFoIM8EjFGcl12o0+q+MO1pcM07ulwOdknfWzYc7x7COior7dd41r3dShX32DD2+ohViXJP0qaKK1uRrJrUsYTb568+sAtGlFH4L3ADWGuBJLrbge9Rwr+R2p6gINrTBW2qLoGZK6R1xHKHilfl8QSrs1JbAvOGHTk3+TgeSXhOnbNRzJ/wp1P5KiKmj5qY2xoXiubDrTmCKObjGriN7ymri8691ZbIj71ki+mXLkby4wShyeT35icOFLY4Myqdwvt0x0hqv539CkQcMm+3nhiwA9u4PzjNMB3LXj/aVnMoIH4pETP4e4zMNYI88fCjrv9qEik=
  template:
    metadata:
      name: questify-stats-db
      namespace: questify
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: questify-admin-db
  namespace: questify
spec:
  encryptedData:
    password: AgAH9bmbsWQrV8kQlTEb4kgDKmaWRk328qjhfnzYSR0wexdF0HYrzR/+aQYLG3p2/2YMe4ILcoh/k8I6wcujusJkG8zEnMyrsx7bw4/4EFh5ME5VMnJq0/47pqaz7D9AyOlbM8zXzQin3LV7Fq5X9CdOjcb7ZAeCtgXdP/GDIVddQmt8BCpxwHg1nN396XkNUp/sJ5AmJeR0qTrYgSdwOYWVPRdlWfC+sCrBSWaicKhnaHS0aa0iv8w71oniirc5GEuJEbHhGi/0IY4YurJqTxtH/ATduKY8qNRUzvfEHn9E5tx7WHN+yVcQh4rt9/xEGJvv5ldySXsnf38nSR306aj6NQqcX1kpX2vxIpIgnr2sPvZDswbGBDu53Hc2ks2FLIBc/3wlEpUJ8Fxy7V8ePqsXyBNFROChsL7BGyrw0o6GIBUGsvuhFd2vMeYFb0MVlj+EzptutaJzwXdqvIQNMUTEJfScCd7eNtq0tx0ebfJ5goW4QAaIHCJNijNL1rl84rM9/BgP81LHe8x+Yg8yoFkxSKTHw4p4raGIMICWupltY/l8fTwOT3KYlOOCZanqAtZkdO/IbnvVrAdChN5TKiALrhqcu9xXyYntpniAw7XvCpa4nIbM4+WUXMmJpvdKRDwUHqzo0VPClC2hHmI9EM1sZW3QUabTz6gpUDctV5x/GghFLcE+u+pgrIb64K3z32Z7/+4vmvzWxSfIDZvQQxLwqWoyzusbFp9Ds1zw56cqeg==
    username: AgCdYJI8uusQSD3fcf4dV4WYqx6QbQlVwh9XvJtRnueJVMClTYUZlU58ouaUFYQJJ7ld4q0m0a8ZjQNdtu5eO0TqVzWVmdTH5u+BiZzO1+uf6ieaS3Qmg1wNh5hKFj4kN/gvz7SdgbdF+1AfqsPMK10li7AzoTWgozULSyBTugpVqb3jP1bh9mVg+9+Ra8rDr95bo+ojCfKvwER4kY35qdfGoue4oaepxVnXhUX8Dc6fQ5iDiWQBwg8NCgRjuD9KpS/N9rgn2NLqJlFZvqD8MXE5GSJb7MmK5MIIvsan0C502s929XTKRs5cAf9rP9LqVpKpeW7AW23mJWSSlx1jrLYqvonGb4UbBXTQu2a+WuxfUfpCGOWa+0BxYzvUA5Y8KMkbAPCjqwS2YppS2miTLbSs9E+ZKJMLRTg3thL2Gb7MFAMGFDOwfRG6ChNsNVvdVHL2HTt6ERtEC22ZGxmz6CYrt/vzns3qB/vBHW8ek4sld6CD3WFXruU6W5nZUK/IgKDZqrULOKpG6dCeNiFy7TfghX9QIZGRjw4HXSO9C4uJ4acgauz1TW9ajdeJaZXZb4h98Wm+IkUdtLg8T99MvI2lLBgJKaSVOQIkJeASMXuFxVxdnI002yVOAYdUXqLyOxoQS4w0o6zJ2pd5HYbD2eAKEQJJrlopCdhat6zTyePepiPgHgDYQTQ37weDtITjwjXnwMsp+svpfS0=
  template:
    metadata:
      name: questify-admin-db
      namespace: questify
